// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vSEwnbwEVhV7Iui4Q5iqqngCydsgwnY',
    appId: '1:989099078651:web:8fe723ca67dac9b687915e',
    messagingSenderId: '989099078651',
    projectId: 'einkaufs-app-9da01',
    authDomain: 'einkaufs-app-9da01.firebaseapp.com',
    storageBucket: 'einkaufs-app-9da01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGpeiGreMUayGVxy45ozPcmMwDzewCBTs',
    appId: '1:989099078651:android:a84b993554c6d1ec87915e',
    messagingSenderId: '989099078651',
    projectId: 'einkaufs-app-9da01',
    storageBucket: 'einkaufs-app-9da01.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vSEwnbwEVhV7Iui4Q5iqqngCydsgwnY',
    appId: '1:989099078651:web:abc1f95082de993b87915e',
    messagingSenderId: '989099078651',
    projectId: 'einkaufs-app-9da01',
    authDomain: 'einkaufs-app-9da01.firebaseapp.com',
    storageBucket: 'einkaufs-app-9da01.appspot.com',
  );
}
